<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ReleaseVersion>2.1.0.0</ReleaseVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Galactic.EventLog\Galactic.EventLog.csproj" />
    <ProjectReference Include="..\Galactic.FileSystem\Galactic.FileSystem.csproj" />
  </ItemGroup>

</Project>
