using System;
using System.IO;
using System.Security.Cryptography;
using System.Text;

namespace Galactic.Cryptography
{
    /// <summary>
    /// AES256 is a class that allows for the easy encryption and decryption of strings
    /// using the AES 256 encryption algorithm.
    /// </summary>
    public class AES256
    {
        // ----- CONSTANTS -----

        // ----- VARIABLES -----

        // ----- PROPERTIES -----

        // ----- CONSTRUCTORS -----

        // ----- METHODS -----

        /// <summary>
        /// Generates a random initialization vector for use by the encryption algorithm.
        /// </summary>
        /// <returns>A random array of bytes, or an empty byte array if the IV could not be
        /// generated.</returns>
        static public byte[] GenerateIV()
        {
            // Generate a random initialization vector.
            try
            {
                RijndaelManaged rm = new RijndaelManaged();
                rm.GenerateIV();
                return rm.IV;
            }
            catch (InvalidOperationException)
            {
                // The RijndaelManaged class is not compliant with the FIPS algorithm.
                return new byte[0];
            }
        }

        /// <summary>
        /// Generates a string representation of an array of bytes.
        /// </summary>
        /// <param name="bytes">The bytes to convert.</param>
        /// <returns>A string representation of an array of bytes, or null if
        /// the string is too large to convert successfully.</returns>
        static public string BytesToString(byte[] bytes)
        {
            if (bytes != null && bytes.Length > 0)
            {
                StringBuilder builder = new StringBuilder();
                foreach (byte b in bytes)
                {
                    try
                    {
                        builder.Append(b);
                        builder.Append(',');
                    }
                    catch (ArgumentOutOfRangeException)
                    {
                        // Enlarging the value of the builder instance would exceed MaxCapacity.
                        return null;
                    }
                }
                builder.Remove(builder.Length - 1, 1);
                return builder.ToString();
            }
            return null;
        }

        /// <summary>
        /// Generates a byte representation of a string generated by BytesToString().
        /// </summary>
        /// <param name="text">The string to convert.</param>
        /// <returns>A byte representation of the string, or any empty byte array if the string could not
        /// be successfully converted.</returns>
        static public byte[] StringToBytes(string text)
        {
            if (!string.IsNullOrWhiteSpace(text))
            {
                string[] strings = text.Split(',');
                byte[] bytes = new byte[strings.Length];
                for (int i = 0; i < strings.Length; i++)
                {
                    if (!string.IsNullOrWhiteSpace(strings[i]))
                    {
                        try
                        {
                            bytes[i] = Byte.Parse(strings[i]);
                        }
                        catch (FormatException)
                        {
                            // strings[i] is not of the correct format.
                            return new byte[0];
                        }
                        catch (OverflowException)
                        {
                            // strings[i[ represents a number less than MinValue or greater than MaxValue.
                            return new byte[0];
                        }
                    }
                }
                return bytes;
            }
            return null;
        }

        /// <summary>
        /// Generates a random key for use by the encryption algorithm.
        /// </summary>
        /// <returns>A random array of bytes, or an empty byte array if the key could not be
        /// generated.</returns>
        static public byte[] GenerateKey()
        {
            // Generate a random key.
            try
            {
                RijndaelManaged rm = new RijndaelManaged();
                rm.GenerateKey();
                return rm.Key;
            }
            catch (InvalidOperationException)
            {
                // The RijndaelManaged class is not compliant with the FIPS algorithm.
                return new byte[0];
            }
        }

        /// <summary>
        /// Encrypts a string of text to an array of AES 256 encrypted bytes. 
        /// </summary>
        /// <param name="text">The text to encrypt.</param>
        /// <param name="key">The key used by the encryption algorithm.</param>
        /// <param name="iv">The initialization vector used by the encryption algorithm.</param>
        /// <returns>An encrypted array of bytes, or an empty array of bytes if the string could not
        /// be encrypted.</returns>
        static public byte[] EncryptStringToBytes(string text, byte[] key, byte[] iv)
        {
            // Check the arguments.
            if (string.IsNullOrWhiteSpace(text))
            {
                throw new ArgumentNullException("text");
            }
            if (key == null || key.Length <= 0)
            {
                throw new ArgumentNullException("key");
            }
            if (iv == null || iv.Length <= 0)
            {
                throw new ArgumentNullException("iv");
            }

            // Declare the stream used to encrypt to an in memory array of bytes.
            MemoryStream msEncrypt = null;

            // Declare the RijndaelManaged object used to encrypt the data.
            RijndaelManaged aesAlg = null;

            try
            {
                // Create a RijndaelManaged object with the specified key and IV.
                aesAlg = new RijndaelManaged();
                try
                {
                    aesAlg.Key = key;
                    try
                    {
                        aesAlg.IV = iv;

                        // Create an encryptor to perform the stream transform.
                        ICryptoTransform encryptor = null;
                        try
                        {
                            encryptor = aesAlg.CreateEncryptor(aesAlg.Key, aesAlg.IV);

                            // Create the streams used for encryption.
                            msEncrypt = new MemoryStream();

                            CryptoStream csEncrypt = null;
                            try
                            {
                                csEncrypt = new CryptoStream(msEncrypt, encryptor, CryptoStreamMode.Write);

                                StreamWriter swEncrypt = null;
                                try
                                {
                                    swEncrypt = new StreamWriter(csEncrypt);

                                    //Write all data to the stream.
                                    try
                                    {
                                        swEncrypt.Write(text);
                                    }
                                    catch (ObjectDisposedException)
                                    {
                                        // AutoFlush is true of the StreamWriter buffer is full, and the current writer is closed.
                                        return new byte[0];
                                    }
                                    catch (NotSupportedException)
                                    {
                                        // AutoFlush is true or the StreamWriter buffer is full, and the contents of the buffer
                                        // can not be written to the underlying fixed size stream because the StreamWriter is
                                        // at the end of the stream.
                                        return new byte[0];
                                    }
                                    catch (IOException)
                                    {
                                        // An I/O error occurred.
                                        return new byte[0];
                                    }
                                }
                                catch (ArgumentException)
                                {
                                    // The StreamWriter is not writable.
                                    return new byte[0];
                                }
                                finally
                                {
                                    // Close the StreamWriter.
                                    if (swEncrypt != null)
                                    {
                                        swEncrypt.Close();
                                    }
                                }
                            }
                            catch (ArgumentException)
                            {
                                // The CryptoStream is not readable, or writeable, or is invalid.
                                return new byte[0];
                            }
                            finally
                            {
                                // Clear the CryptoStream.
                                if (csEncrypt != null)
                                {
                                    csEncrypt.Clear();
                                }
                            }
                        }
                        catch (CryptographicException)
                        {
                            // The value of the ICryptoTransform's Mode parameter is not ECB, CBC, or CFB.
                            return new byte[0];
                        }
                        finally
                        {
                            // Dispose of the ICryptoTransform.
                            if (encryptor != null)
                            {
                                encryptor.Dispose();
                            }
                        }
                    }
                    catch (CryptographicException)
                    {
                        // An attempt was made to set the initialization vector to an invalid size.
                        return new byte[0];
                    }
                }
                catch (CryptographicException)
                {
                    // The key size is invalid.
                    return new byte[0];
                }
            }
            catch (InvalidOperationException)
            {
                // The RijndaelManaged class is not compliant with the FIPS algorithm.
                return new byte[0];
            }
            finally
            {
                // Clear the RijndaelManaged object.
                if (aesAlg != null)
                {
                    aesAlg.Clear();
                }
            }

            // Return the encrypted bytes from the memory stream.
            return msEncrypt.ToArray();
        }

        /// <summary>
        /// Decrypts an array of AES 256 encrypted bytes to a plain text string. 
        /// </summary>
        /// <param name="cipherText">The bytes to decrypt.</param>
        /// <param name="key">The key used by the decryption algorithm.</param>
        /// <param name="iv">The initialization vector used by the decryption algorithm.</param>
        /// <returns>The decrypted string, or null if the byte array could not be decrypted.</returns>
        static public string DecryptStringFromBytes(byte[] cipherText, byte[] key, byte[] iv)
        {
            // Check arguments.
            if (cipherText == null || cipherText.Length <= 0)
            {
                throw new ArgumentNullException("cipherText");
            }
            if (key == null || key.Length <= 0)
            {
                throw new ArgumentNullException("key");
            }
            if (iv == null || iv.Length <= 0)
            {
                throw new ArgumentNullException("iv");
            }

            // Declare the RijndaelManaged object used to decrypt the data.
            RijndaelManaged aesAlg = null;

            // Declare the string used to hold the decrypted text.
            string text = null;

            try
            {
                // Create a RijndaelManaged object with the specified key and IV.
                aesAlg = new RijndaelManaged();
                try
                {
                    aesAlg.Key = key;
                    try
                    {
                        aesAlg.IV = iv;

                        // Create a decryptor to perform the stream transform.
                        ICryptoTransform decryptor = null;
                        try
                        {
                            decryptor = aesAlg.CreateDecryptor(aesAlg.Key, aesAlg.IV);
                            // Create the streams used for decryption.
                            using (MemoryStream msDecrypt = new MemoryStream(cipherText))
                            {
                                CryptoStream csDecrypt = null;
                                try
                                {
                                    csDecrypt = new CryptoStream(msDecrypt, decryptor, CryptoStreamMode.Read);

                                    StreamReader srDecrypt = null;
                                    try
                                    {
                                        srDecrypt = new StreamReader(csDecrypt);

                                        // Read the decrypted bytes from the decrypting stream
                                        // and place them in a string.
                                        try
                                        {
                                            text = srDecrypt.ReadToEnd();
                                        }
                                        catch (OutOfMemoryException)
                                        {
                                            // There is insufficient memory to allocate a buffer for the returned string.
                                            return null;
                                        }
                                        catch (IOException)
                                        {
                                            // An I/O error occurred.
                                            return null;
                                        }
                                        finally
                                        {
                                            // Close the StreamReader.
                                            if (srDecrypt != null)
                                            {
                                                srDecrypt.Close();
                                            }
                                        }
                                    }
                                    catch (ArgumentException)
                                    {
                                        // The StreamReader does not support reading.
                                        return null;
                                    }
                                    finally
                                    {
                                        // Close the StreamReader.
                                        if (srDecrypt != null)
                                        {
                                            srDecrypt.Close();
                                        }
                                    }
                                }
                                catch (ArgumentException)
                                {
                                    // The CryptoStream is not readable, or writeable, or is invalid.
                                    return null;
                                }
                                finally
                                {
                                    // Clear the CryptoStream.
                                    if (csDecrypt != null)
                                    {
                                        csDecrypt.Clear();
                                    }
                                }
                            }
                        }
                        catch (CryptographicException)
                        {
                            // The value of the ICryptoTransform's Mode parameter is not ECB, CBC, or CFB.
                            return null;
                        }
                        finally
                        {
                            // Dispose of the ICryptoTransform.
                            if (decryptor != null)
                            {
                                decryptor.Dispose();
                            }
                        }
                    }
                    catch (CryptographicException)
                    {
                        // An attempt was made to set the initialization vector to an invalid size.
                        return null;
                    }
                }
                catch (CryptographicException)
                {
                    // The key size is invalid.
                    return null;
                }
            }
            catch (InvalidOperationException)
            {
                // The RijndaelManaged class is not compliant with the FIPS algorithm.
                return null;
            }
            finally
            {
                // Clear the RijndaelManaged object.
                if (aesAlg != null)
                    aesAlg.Clear();
            }

            return text;
        }
    }
}
