// Thanks to Vagif Abilov, for this elegant solution, available here:
// http://vagif.bloggingabout.net/2010/04/24/using-t4-templates-to-manage-assembly-version-information/
// 
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// 

using System.Reflection;

[assembly: AssemblyVersion("1.3.0.116")]
[assembly: AssemblyFileVersion("1.3.0.116")]
